// Mapping from real 2020 NYC NTA names to CTY neighborhood IDs
// NTAs not mapped still render as part of the city shape (dark background)

const NTA_TO_CTY = {
  // ─── Manhattan ──────────────────────────────────────────
  'Financial District-Battery Park City': 'financial_district',
  'Tribeca-Civic Center': 'tribeca',
  'SoHo-Little Italy-Hudson Square': 'soho',
  'Chinatown-Two Bridges': 'chinatown',
  'Lower East Side': 'lower_east_side',
  'East Village': 'east_village',
  'West Village': 'west_village',
  'Greenwich Village': 'greenwich_village',
  'Chelsea-Hudson Yards': 'chelsea',
  'Gramercy': 'gramercy',
  'Stuyvesant Town-Peter Cooper Village': 'gramercy',
  'Murray Hill-Kips Bay': 'murray_hill',
  'East Midtown-Turtle Bay': 'murray_hill',
  'Midtown South-Flatiron-Union Square': 'flatiron',
  'Midtown-Times Square': 'midtown',
  "Hell's Kitchen": 'hell_kitchen',
  'Upper West Side (Central)': 'upper_west_side',
  'Upper West Side-Lincoln Square': 'upper_west_side',
  'Upper West Side-Manhattan Valley': 'upper_west_side',
  'Upper East Side-Lenox Hill-Roosevelt Island': 'upper_east_side',
  'Upper East Side-Carnegie Hill': 'upper_east_side',
  'Upper East Side-Yorkville': 'upper_east_side',
  'East Harlem (North)': 'harlem',
  'East Harlem (South)': 'harlem',
  'Harlem (North)': 'harlem',
  'Harlem (South)': 'harlem',
  'Manhattanville-West Harlem': 'harlem',
  'Morningside Heights': 'harlem',
  'Hamilton Heights-Sugar Hill': 'harlem',
  'Washington Heights (South)': 'washington_heights',
  'Washington Heights (North)': 'washington_heights',
  'Inwood': 'washington_heights',

  // ─── Brooklyn ──────────────────────────────────────────
  'Greenpoint': 'greenpoint',
  'Williamsburg': 'williamsburg',
  'East Williamsburg': 'williamsburg',
  'South Williamsburg': 'williamsburg',
  'Downtown Brooklyn-DUMBO-Boerum Hill': 'dumbo',
  'Brooklyn Heights': 'brooklyn_heights',
  'Park Slope': 'park_slope',
  'Windsor Terrace-South Slope': 'park_slope',
  'Prospect Heights': 'prospect_heights',
  'Crown Heights (North)': 'crown_heights',
  'Crown Heights (South)': 'crown_heights',
  'Prospect Lefferts Gardens-Wingate': 'crown_heights',
  'Bedford-Stuyvesant (West)': 'bed_stuy',
  'Bedford-Stuyvesant (East)': 'bed_stuy',
  'Ocean Hill': 'bed_stuy',
  'Bushwick (West)': 'bushwick',
  'Bushwick (East)': 'bushwick',
  'Sunset Park (Central)': 'sunset_park',
  'Sunset Park (West)': 'sunset_park',
  'Sunset Park (East)-Borough Park (West)': 'sunset_park',
  'Bay Ridge': 'bay_ridge',
  'Dyker Heights': 'bay_ridge',
  'Carroll Gardens-Cobble Hill-Gowanus-Red Hook': 'cobble_hill',
  'Fort Greene': 'fort_greene',
  'Clinton Hill': 'fort_greene',

  // ─── Queens ──────────────────────────────────────────
  'Astoria (Central)': 'astoria',
  'Astoria (North)-Ditmars-Steinway': 'astoria',
  'Astoria (East)-Woodside (North)': 'astoria',
  'Old Astoria-Hallets Point': 'astoria',
  'Long Island City-Hunters Point': 'long_island_city',
  'Queensbridge-Ravenswood-Dutch Kills': 'long_island_city',
  'Sunnyside': 'sunnyside',
  'Jackson Heights': 'jackson_heights',
  'East Elmhurst': 'jackson_heights',
  'Elmhurst': 'jackson_heights',
  'Flushing-Willets Point': 'flushing',
  'Murray Hill-Broadway Flushing': 'flushing',
  'East Flushing': 'flushing',
  'Queensboro Hill': 'flushing',
  'Forest Hills': 'forest_hills',
  'Rego Park': 'forest_hills',
  'Kew Gardens': 'forest_hills',
  'Woodside': 'woodside',
  'Maspeth': 'woodside',
  'Middle Village': 'woodside',
  'Jamaica': 'jamaica',
  'Jamaica Estates-Holliswood': 'jamaica',
  'South Jamaica': 'jamaica',
  'Jamaica Hills-Briarwood': 'jamaica',
  'Ridgewood': 'ridgewood',
  'Glendale': 'ridgewood',
  'Bayside': 'bayside',
  'Bay Terrace-Clearview': 'bayside',
  'Douglaston-Little Neck': 'bayside',
  'Rockaway Beach-Arverne-Edgemere': 'rockaway_beach',
  'Breezy Point-Belle Harbor-Rockaway Park-Broad Channel': 'rockaway_beach',
  'Far Rockaway-Bayswater': 'rockaway_beach',
  'Corona': 'corona',
  'North Corona': 'corona',
  'Woodhaven': 'woodside',

  // ─── Bronx ──────────────────────────────────────────
  'Mott Haven-Port Morris': 'mott_haven',
  'Melrose': 'south_bronx',
  'Longwood': 'south_bronx',
  'Morrisania': 'south_bronx',
  'Claremont Village-Claremont (East)': 'south_bronx',
  'Crotona Park East': 'south_bronx',
  'Highbridge': 'south_bronx',
  'Concourse-Concourse Village': 'south_bronx',
  'Mount Eden-Claremont (West)': 'south_bronx',
  'Mount Hope': 'south_bronx',
  'Hunts Point': 'hunts_point',
  'Soundview-Bruckner-Bronx River': 'hunts_point',
  'Soundview-Clason Point': 'hunts_point',
  'Castle Hill-Unionport': 'hunts_point',
  'Fordham Heights': 'fordham',
  'University Heights (North)-Fordham': 'fordham',
  'University Heights (South)-Morris Heights': 'fordham',
  'Bedford Park': 'fordham',
  'Norwood': 'fordham',
  'Kingsbridge Heights-Van Cortlandt Village': 'fordham',
  'Kingsbridge-Marble Hill': 'fordham',
  'Belmont': 'belmont',
  'Tremont': 'belmont',
  'West Farms': 'belmont',
  'Morris Park': 'belmont',
  'Riverdale-Spuyten Duyvil': 'riverdale',
  'Pelham Bay-Country Club-City Island': 'pelham_bay',
  'Pelham Parkway-Van Nest': 'pelham_bay',
  'Pelham Gardens': 'pelham_bay',
  'Westchester Square': 'pelham_bay',
  'Throgs Neck-Schuylerville': 'pelham_bay',
  'Allerton': 'pelham_bay',
  'Williamsbridge-Olinville': 'pelham_bay',
  'Parkchester': 'pelham_bay',

  // ─── Staten Island ──────────────────────────────────
  'St. George-New Brighton': 'st_george',
  'Tompkinsville-Stapleton-Clifton-Fox Hills': 'st_george',
  'Rosebank-Shore Acres-Park Hill': 'st_george',
  'Grasmere-Arrochar-South Beach-Dongan Hills': 'st_george',
  'Tottenville-Charleston': 'tottenville',
  "Annadale-Huguenot-Prince's Bay-Woodrow": 'tottenville',
  'Arden Heights-Rossville': 'tottenville',
  'Great Kills-Eltingville': 'tottenville',
  'New Dorp-Midland Beach': 'historic_richmond_town',
  'Todt Hill-Emerson Hill-Lighthouse Hill-Manor Heights': 'historic_richmond_town',
  'Oakwood-Richmondtown': 'historic_richmond_town',
  'Westerleigh-Castleton Corners': 'snug_harbor',
  'West New Brighton-Silver Lake-Grymes Hill': 'snug_harbor',
  'Port Richmond': 'snug_harbor',
  "Mariner's Harbor-Arlington-Graniteville": 'snug_harbor',
  'New Springville-Willowbrook-Bulls Head-Travis': 'snug_harbor',
};

// Reverse mapping: CTY ID -> array of NTA names
const CTY_TO_NTAS = {};
Object.entries(NTA_TO_CTY).forEach(([nta, cty]) => {
  if (!CTY_TO_NTAS[cty]) CTY_TO_NTAS[cty] = [];
  CTY_TO_NTAS[cty].push(nta);
});
